Extract base-path from public URLs and use it as prefix for all service endpoint URLs
palantir/policy-bot pull request #117
Opened 2019-08-22 16:09 UTC by bgutjahr

We want to run policy-bot docker container in a kubernetes pod.
In our enviroment, we tried to configure a public URL like this:
  https://out-host-name:443/policy-bot
Initially we configured the ingress (nginx) web proxy to map that URL to the
policy-bot kubernetes service (mapped to the policy-bot container's local port,
and to strip off the external-URLs /policy-bot base-path from the URL.

This approach didn't work, since the policy-bot container used it's own URLs (not the public URL)
for oauth redirects.

My solution is to extend policy-bot to extract the path from the public URL as use
is as a base-path for all handled and redirected URLs.

Then we could configure the ingress proxy to just pass the .../policy-bot URL unchanged to the
container, and everything worked smoothly.

2019-08-22 16:09 UTC, palantirtech commented
Thanks for your interest in [palantir/policy-bot](https://github.com/palantir/policy-bot), @bgutjahr! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2019-08-26 22:45 UTC, bluekeyes requested changes
Thanks for implementing this! We hadn't considered deployments that use prefix paths since we usually use subdomains. I had a few suggestions on the implementation, but the concept is sound.

2019-08-26 22:45 UTC, bluekeyes commented on server/server.go
> +	mux.Handle(pat.Post(basePath+githubapp.DefaultWebhookRoute), dispatcher)
Instead of adding `basePath` to each route, I'd use a sub-mux instead, something like this (untested):

```golang
var mux *goiji.Mux
if basePath == "" {
  mux = base.Mux()
} else {
  mux = goji.SubMux()
  base.Mux().Handle(pat.New(basePath+"/*"), mux)
}
```

That way, all the route definitions can remain the same.

2019-08-26 22:45 UTC, bluekeyes commented on server/server.go
> +	logger.Info().Msg("BasePath = " + basePath)
Since we don't log any other configuration right now (although maybe we should), can you remove this?

2019-08-29 08:14 UTC, bgutjahr commented on server/server.go
> +	logger.Info().Msg("BasePath = " + basePath)
I have made the suggested changes.
What I'm not fully sure about: is prepending the basePath in "handler.Static(basePath+"/static/", ..." (server.go, line 157) correct?

2019-08-30 20:43 UTC, bluekeyes approved these changes
Yes, the change to the static paths looks correct to me.

2019-08-30 20:45 UTC, merged